# Generated by Django 4.1.7 on 2023-08-12 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
